[package]
name = "simple-ffi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "simple_ffi"
crate-type = ["rlib" , "cdylib"]


[dependencies]
